import type { ReactNode } from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

interface RootLayoutProps {
  children: ReactNode;
}

const metadata = {
  title: 'Next.js Application Template',
  description: 'Generated by ics-software-engineering.github.io',
};

export default function RootLayout({ children }: RootLayoutProps) {
  const classString = `${inter.className} wrapper`;
  
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{`body { margin: 0 }`}</style>
      </Head>
      <body className={classString}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
